export const CATEGORIES = {
  CONST: "Constitutional Law",
  CIVIL: "Civil Law",
  CRIM: "Criminal Law",
  REM: "Remedial Law",
  GEN: "General Legal Terms",
  MAXIM: "Legal Maxims / Latin Terms",
};

// Starter set of first-year terms. Each object maps directly onto the
// shape of a row in the `terms` table (see supabase/schema.sql), minus
// id/user_id/created_at which the database assigns.
export const SEED_TERMS = [
  {
    term: "Jurisprudence",
    category: CATEGORIES.GEN,
    difficulty: "beginner",
    simple: "The body of court decisions that explain and apply the law.",
    legal:
      "The collection of adjudicated cases dealing with a particular subject, or the philosophy and science of law as developed through court decisions.",
    beginner:
      "Think of jurisprudence as everything the courts have already said about a legal question. When a statute is unclear, jurisprudence tells you how judges have actually applied it in real cases.",
    why: "In the Philippines, jurisprudence from the Supreme Court forms part of the legal system under Article 8 of the Civil Code. You cannot argue a legal position well without knowing how the Court has ruled on it.",
    example:
      "When studying due process, you read not just the Constitution but also cases like Ang Tibay v. CIR to see how the Court has interpreted it.",
    memory_tip: "Juris (law) + prudence (wisdom) — the accumulated wisdom of the law.",
    latin: null,
    related_laws: ["Article 8, Civil Code"],
    cases: ["Ang Tibay v. Court of Industrial Relations"],
    related: ["Doctrine", "Stare Decisis", "Statute"],
  },
  {
    term: "Mandatory Law",
    category: CATEGORIES.GEN,
    difficulty: "beginner",
    simple: "A law that must be followed. You cannot opt out of it by agreement.",
    legal:
      "A law that commands or prohibits something in a way that cannot be waived or altered by private agreement, as opposed to a permissive or suppletory rule.",
    beginner:
      "If a law is mandatory, no contract or agreement between parties can override it. Compare this to a suppletory rule, which only applies when the parties haven't agreed on something themselves.",
    why: "Knowing whether a rule is mandatory or merely suppletory tells you whether the parties to a contract can validly deviate from it.",
    example: "The requirement that marriage be solemnized by an authorized officer is mandatory; you cannot contract around it.",
    memory_tip: "Mandatory = Must. Both start with 'M'.",
    latin: null,
    related_laws: ["Article 5, Civil Code"],
    cases: [],
    related: ["Procedural Law", "Statute"],
  },
  {
    term: "Procedural Law",
    category: CATEGORIES.GEN,
    difficulty: "beginner",
    simple: "The rules on how to enforce your rights in court, not what the rights actually are.",
    legal:
      "That branch of law which prescribes the method of enforcing rights or obtaining redress for their invasion; it deals with the machinery for carrying on the suit.",
    beginner:
      "Substantive law tells you what your rights are, like the right to recover a debt. Procedural law tells you how to go to court to actually get that debt paid, meaning which court, what documents, what deadlines.",
    why: "Getting the procedure wrong, like filing in the wrong court or missing a deadline, can lose an otherwise winnable case. This is why Remedial Law is such a heavily tested bar subject.",
    example: "The Rules of Civil Procedure telling you how many days you have to file an answer to a complaint is procedural law.",
    memory_tip: "Procedural = Process. It is the 'how,' not the 'what.'",
    latin: null,
    related_laws: ["Rules of Court"],
    cases: [],
    related: ["Mandatory Law", "Cause of Action", "Certiorari"],
  },
  {
    term: "Lex Rei Sitae",
    category: CATEGORIES.MAXIM,
    difficulty: "intermediate",
    simple: "The law of the place where the property is located governs that property.",
    legal:
      "A conflict-of-laws principle providing that real and personal property is generally governed by the law of the country where it is situated.",
    beginner:
      "If you own land in Japan but live in the Philippines, Japanese law generally governs questions about that land, like how it can be transferred or inherited.",
    why: "This comes up constantly in Private International Law and in Article 16 of the Civil Code, which is a favorite bar exam topic.",
    example: "A dispute over who inherits a condominium unit in Singapore would generally be resolved using Singaporean property law.",
    memory_tip: "'Rei Sitae' sounds like 'where it sits' — the law follows where the property sits.",
    latin: "Lex (law) + rei (of the thing) + sitae (situated) — 'the law of the place where the thing is situated.'",
    related_laws: ["Article 16, Civil Code"],
    cases: [],
    related: ["Retroactive", "Estoppel"],
  },
  {
    term: "Due Process",
    category: CATEGORIES.CONST,
    difficulty: "intermediate",
    simple: "The government must follow fair rules before it can take your life, liberty, or property.",
    legal:
      "A constitutional guarantee that no person shall be deprived of life, liberty, or property without due process of law, encompassing both substantive due process (fairness of the law itself) and procedural due process (fairness of the manner of enforcement).",
    beginner:
      "Split due process into two boxes. Substantive due process asks: is the law itself fair and reasonable? Procedural due process asks: was the person given proper notice and a chance to be heard before losing something?",
    why: "Due process is the backbone of Constitutional Law and shows up in criminal procedure, administrative cases, and even school discipline cases.",
    example:
      "A student who is expelled without ever being told the charges against him or given a chance to explain his side has a procedural due process complaint.",
    memory_tip: "Due process = you are 'due' a fair process before the government can hurt you.",
    latin: null,
    related_laws: ["Article III, Section 1, 1987 Constitution"],
    cases: ["Ang Tibay v. Court of Industrial Relations", "Vargas v. Rilloraza"],
    related: ["Presumption of Innocence", "Bill of Rights", "Judicial Review"],
  },
  {
    term: "Estoppel",
    category: CATEGORIES.CIVIL,
    difficulty: "intermediate",
    simple: "You cannot deny something you previously represented as true if someone relied on it.",
    legal:
      "A bar which precludes a person from denying or asserting anything contrary to that which has been established as the truth, whether by his own act, representation, or omission, on which another relied.",
    beginner:
      "Imagine you tell your neighbor you don't own a piece of land, and he buys it from someone else relying on your word. Later, you cannot suddenly claim ownership of that same land, because your earlier statement stopped you.",
    why: "Estoppel protects people who reasonably rely on another party's words or conduct, and it appears constantly in Civil Law, Corporation Law, and Evidence.",
    example: "A landlord who repeatedly accepted late rent without objection may be estopped from suddenly evicting a tenant for being late, without prior warning.",
    memory_tip: "Estoppel sounds like 'stop.' It stops you from contradicting yourself.",
    latin: null,
    related_laws: ["Article 1431, Civil Code", "Rule 131, Rules of Court"],
    cases: [],
    related: ["Bad Faith", "Res Judicata"],
  },
  {
    term: "Retroactive (Retroactivity of Laws)",
    category: CATEGORIES.GEN,
    difficulty: "beginner",
    simple: "A law that reaches back and applies to events that already happened before it existed.",
    legal:
      "The general rule is that laws have prospective effect only, unless the law itself expressly provides for retroactive application, and such retroactivity must not impair vested rights or, in criminal law, prejudice the accused.",
    beginner:
      "The default rule is 'laws look forward, not backward.' A new law usually applies only to acts done after it takes effect, unless the law says otherwise, and even then, it can't be used to punish someone for something that wasn't a crime when they did it.",
    why: "This connects directly to the constitutional ban on ex post facto laws in Criminal Law, and to Article 4 of the Civil Code.",
    example: "If Congress passes a new tax law today, it normally cannot be used to tax income earned last year.",
    memory_tip: "Retro = 'backward looking,' like retro fashion looking back to old styles.",
    latin: null,
    related_laws: ["Article 4, Civil Code"],
    cases: [],
    related: ["Ex Post Facto Law", "Lex Rei Sitae"],
  },
  {
    term: "Habitual Delinquency",
    category: CATEGORIES.CRIM,
    difficulty: "advanced",
    simple: "Being convicted of certain crimes again and again within a set period of time.",
    legal:
      "Under Article 62 of the Revised Penal Code, a person is a habitual delinquent when, within a period of ten years from the date of release or last conviction of specific crimes such as serious or less serious physical injuries, robbery, theft, estafa, or falsification, he is found guilty of any of said crimes a third time or oftener.",
    beginner:
      "This is not just 'being a repeat offender' in a general sense. It only applies to a specific list of crimes, and it counts convictions within a strict ten year window. Getting caught the third time within that window triggers this special aggravating rule.",
    why: "Habitual delinquency adds an extra penalty on top of the usual one and is a common source of tricky bar questions because students confuse it with plain recidivism.",
    example: "A person convicted of theft three separate times within ten years may be found a habitual delinquent, with additional penalties on top of the theft sentence itself.",
    memory_tip: "Think '3 strikes, 1 specific list, 10 year clock.'",
    latin: null,
    related_laws: ["Article 62, Revised Penal Code"],
    cases: [],
    related: ["Mala in Se", "Mala Prohibita"],
  },
  {
    term: "Action in Rem",
    category: CATEGORIES.REM,
    difficulty: "intermediate",
    simple: "A lawsuit directed against a thing itself, not against a specific person.",
    legal:
      "An action directed against the thing itself, binding the whole world, as distinguished from an action in personam which is directed against a specific person.",
    beginner:
      "In an action in rem, the court is really deciding who has rights over a piece of property or status, like land or a person's civil status, and that decision is binding on everyone, not just whoever showed up to court.",
    why: "This distinction determines what kind of summons and jurisdiction the court needs, a major topic in Civil Procedure.",
    example: "A land registration case, where the court decides who owns a parcel of land against the whole world, is an action in rem.",
    memory_tip: "'Rem' sounds like 'thing' — remember, action in rem is about the thing.",
    latin: "In rem literally means 'against the thing.'",
    related_laws: ["Rule 14, Rules of Court"],
    cases: [],
    related: ["Action in Personam", "Cause of Action"],
  },
  {
    term: "Contra Bonos Mores",
    category: CATEGORIES.MAXIM,
    difficulty: "intermediate",
    simple: "Against good morals or good customs.",
    legal:
      "A Latin maxim describing acts, contracts, or stipulations that are contrary to good morals, customs, public order, or public policy, and are therefore void.",
    beginner:
      "Even if two people freely agree to something in a contract, courts will refuse to enforce it if the agreement itself is against basic morality or public policy.",
    why: "This concept limits freedom of contract under Article 1306 of the Civil Code and often appears together with questions on void contracts.",
    example: "A contract where someone agrees to pay another person to commit a crime is void for being contra bonos mores.",
    memory_tip: "'Bonos mores' sounds like 'bonus morals' — this is about violating good morals.",
    latin: "Contra (against) + bonos (good) + mores (customs/morals).",
    related_laws: ["Article 1306, Civil Code", "Article 1409, Civil Code"],
    cases: [],
    related: ["Estoppel", "Bad Faith"],
  },
  {
    term: "Action in Personam",
    category: CATEGORIES.REM,
    difficulty: "intermediate",
    simple: "A lawsuit against a specific person, seeking to make that person do or pay something.",
    legal:
      "An action directed against a particular person based on his personal liability, binding only the parties impleaded or their successors in interest, as opposed to an action in rem.",
    beginner: "If you sue someone to collect a debt they personally owe you, that judgment only affects that person, not the whole world.",
    why: "This distinction matters for how summons must be served and whether a court has jurisdiction over the defendant.",
    example: "A collection suit to recover a loan from a specific borrower is an action in personam.",
    memory_tip: "'Personam' sounds like 'person' — action in personam targets a person.",
    latin: "In personam literally means 'against the person.'",
    related_laws: ["Rule 14, Rules of Court"],
    cases: [],
    related: ["Action in Rem", "Cause of Action"],
  },
  {
    term: "Acquittal",
    category: CATEGORIES.CRIM,
    difficulty: "beginner",
    simple: "A court ruling that the accused is not guilty.",
    legal:
      "A judgment that the accused is not guilty of the offense charged, either because the prosecution failed to prove guilt beyond reasonable doubt or because of an exempting or justifying circumstance.",
    beginner: "An acquittal is the opposite of conviction. Because of the presumption of innocence, the prosecution carries the burden of proving guilt, and if it fails, the accused walks free.",
    why: "An acquittal is generally final and immediately executory, and it triggers strong double jeopardy protection against a second prosecution for the same offense.",
    example: "If the only eyewitness against the accused turns out to be unreliable and no other evidence exists, the court will acquit for failure to prove guilt beyond reasonable doubt.",
    memory_tip: "Acquittal = 'a quit all' the charges, the accused is cleared of them.",
    latin: null,
    related_laws: ["Rule 120, Rules of Court"],
    cases: [],
    related: ["Presumption of Innocence", "Due Process"],
  },
  {
    term: "Actus Reus",
    category: CATEGORIES.CRIM,
    difficulty: "beginner",
    simple: "The guilty act, the physical act of committing a crime.",
    legal: "The wrongful deed or overt act that, together with a culpable mental state (mens rea), constitutes a crime.",
    beginner: "A crime generally needs two ingredients: doing something wrong (actus reus) and having a guilty mind while doing it (mens rea). Actus reus is the 'doing' part.",
    why: "Distinguishing actus reus from mens rea helps you analyze whether a criminal act was actually committed, and whether it was voluntary.",
    example: "In theft, the actus reus is the actual taking of another's property without consent.",
    memory_tip: "Actus = act. The act itself, separate from intent.",
    latin: "Actus (act) + reus (guilty) — 'the guilty act.'",
    related_laws: ["Article 3, Revised Penal Code"],
    cases: [],
    related: ["Mens Rea", "Mala in Se"],
  },
  {
    term: "Mens Rea",
    category: CATEGORIES.CRIM,
    difficulty: "beginner",
    simple: "The guilty mind, the mental intent to commit a crime.",
    legal: "The mental element of a crime, referring to the criminal intent or knowledge of wrongdoing that must generally accompany the actus reus for criminal liability to attach.",
    beginner: "This is the 'guilty mind' half of a crime. Even if a harmful act happened, if there was no criminal intent and it wasn't a case of criminal negligence, there may be no crime at all.",
    why: "Mens rea is central to distinguishing intentional felonies from those committed through negligence (culpa) under the Revised Penal Code.",
    example: "Accidentally bumping into someone and causing injury lacks mens rea and is not a felony by dolo, though it might still be culpable if there was negligence.",
    memory_tip: "Mens = mind. The mind behind the act.",
    latin: "Mens (mind) + rea (guilty) — 'the guilty mind.'",
    related_laws: ["Article 3, Revised Penal Code"],
    cases: [],
    related: ["Actus Reus", "Mala in Se", "Mala Prohibita"],
  },
  {
    term: "Mala in Se",
    category: CATEGORIES.CRIM,
    difficulty: "beginner",
    simple: "Acts that are inherently wrong, wrong by their very nature.",
    legal: "Acts or omissions that are inherently evil or immoral, regardless of whether a law punishes them, and for which criminal intent (dolo) or negligence (culpa) is required.",
    beginner: "These are the crimes everyone instinctively knows are wrong, like killing or stealing, even without ever reading a law book. Because they are wrong by nature, intent usually matters in proving them.",
    why: "Most crimes under the Revised Penal Code are mala in se, and this classification affects whether good faith or lack of criminal intent can be a valid defense.",
    example: "Murder and theft are classic examples of mala in se offenses.",
    memory_tip: "'In se' sounds like 'in itself' — wrong in itself.",
    latin: "Mala (evil) + in se (in itself) — 'wrong in itself.'",
    related_laws: ["Revised Penal Code, Act No. 3815"],
    cases: [],
    related: ["Mala Prohibita", "Mens Rea", "Actus Reus"],
  },
  {
    term: "Mala Prohibita",
    category: CATEGORIES.CRIM,
    difficulty: "beginner",
    simple: "Acts that are wrong only because a law says they are prohibited.",
    legal: "Acts that are wrong merely because they are prohibited by a special law or statute, where criminal intent is generally not required, only the intent to commit the prohibited act.",
    beginner: "These acts are not inherently evil, they are only illegal because a statute decided to ban them. Because of this, the usual rule is that it doesn't matter whether you meant to break the law, only that you did the prohibited act.",
    why: "This classification matters heavily for special penal laws, since defenses like good faith or lack of intent generally do not apply the same way they do for mala in se crimes.",
    example: "Driving without a license is mala prohibita, it is illegal because a traffic law says so, not because driving is inherently evil.",
    memory_tip: "'Prohibita' sounds like 'prohibited' — wrong because prohibited.",
    latin: "Mala (evil) + prohibita (prohibited) — 'wrong because prohibited.'",
    related_laws: ["Special Penal Laws"],
    cases: [],
    related: ["Mala in Se", "Habitual Delinquency"],
  },
  {
    term: "Bail",
    category: CATEGORIES.CONST,
    difficulty: "beginner",
    simple: "Security given so an accused person can be released while the case is pending.",
    legal: "The security given for the release of a person in custody of the law, conditioned upon his appearance before any court as required, which may be in the form of cash, corporate surety, property bond, or recognizance.",
    beginner: "Bail lets someone accused of a crime stay out of jail while trial is ongoing, in exchange for a guarantee that they will show up whenever the court requires.",
    why: "The right to bail is constitutionally guaranteed except for offenses punishable by reclusion perpetua when evidence of guilt is strong, making it a favorite topic in both Constitutional Law and Criminal Procedure.",
    example: "An accused charged with a bailable offense posts a cash bond so he can prepare his defense outside of detention.",
    memory_tip: "Bail lets you 'bail out' of jail temporarily while the case continues.",
    latin: null,
    related_laws: ["Article III, Section 13, 1987 Constitution", "Rule 114, Rules of Court"],
    cases: [],
    related: ["Due Process", "Presumption of Innocence"],
  },
  {
    term: "Bill of Rights",
    category: CATEGORIES.CONST,
    difficulty: "beginner",
    simple: "The part of the Constitution that protects individual freedoms from government abuse.",
    legal: "Article III of the 1987 Philippine Constitution, which enumerates the fundamental civil and political rights of individuals and imposes limitations on the powers of the State to safeguard those rights.",
    beginner: "This is the Constitution's list of 'the government cannot do this to you' rules, covering things like due process, free speech, and the right against unreasonable searches.",
    why: "Nearly every Constitutional Law question eventually connects back to a Bill of Rights provision, and many Criminal Procedure rules exist to enforce it.",
    example: "The right against self-incrimination, which lets an accused refuse to testify against himself, comes from the Bill of Rights.",
    memory_tip: "Bill of Rights = the Constitution's 'receipt' of the rights you're entitled to.",
    latin: null,
    related_laws: ["Article III, 1987 Constitution"],
    cases: [],
    related: ["Due Process", "Presumption of Innocence", "Separation of Powers"],
  },
  {
    term: "Capacity (to Act)",
    category: CATEGORIES.CIVIL,
    difficulty: "beginner",
    simple: "The legal power to do acts with legal consequences, like entering a valid contract.",
    legal: "The power to do acts with legal effect, acquired at birth or fixed by law, which may be restricted by circumstances such as minority, insanity, or civil interdiction.",
    beginner: "Every person has 'juridical capacity' just by existing, but 'capacity to act' is the ability to actually perform valid legal acts, like signing a binding contract, and this can be limited for minors or persons of unsound mind.",
    why: "Capacity affects whether a contract is void, voidable, or valid, a core issue in Obligations and Contracts.",
    example: "A contract signed by a seven year old child is voidable because the child lacks full capacity to act.",
    memory_tip: "Capacity = 'can-pass-it-off' as your own valid legal act.",
    latin: null,
    related_laws: ["Article 37, Civil Code", "Article 38, Civil Code"],
    cases: [],
    related: ["Estoppel", "Bad Faith"],
  },
  {
    term: "Cause of Action",
    category: CATEGORIES.REM,
    difficulty: "intermediate",
    simple: "The set of facts that gives a person the right to sue.",
    legal: "The act or omission by which a party violates the right of another, consisting of a legal right of the plaintiff, a correlative obligation of the defendant, and an act or omission of the defendant in violation of that right.",
    beginner: "Before you can sue anyone, you need three things to exist together: you have a right, the other person has a duty to respect it, and they broke that duty. Missing any one of the three means you have no cause of action yet.",
    why: "A complaint that fails to state a cause of action can be dismissed outright, making this one of the first things checked in Civil Procedure.",
    example: "If a debt is not yet due, the creditor has no cause of action to sue for payment until the due date actually arrives.",
    memory_tip: "Cause of action = the 'cause' that lets you take legal 'action.'",
    latin: null,
    related_laws: ["Rule 2, Rules of Court"],
    cases: [],
    related: ["Action in Personam", "Action in Rem", "Procedural Law"],
  },
  {
    term: "Certiorari",
    category: CATEGORIES.REM,
    difficulty: "advanced",
    simple: "A special court action to correct a lower court's grave abuse of discretion.",
    legal:
      "A special civil action filed to annul or modify the proceedings of any tribunal, board, or officer exercising judicial or quasi-judicial functions when it has acted without or in excess of jurisdiction, or with grave abuse of discretion amounting to lack or excess of jurisdiction, and there is no appeal or other adequate remedy.",
    beginner: "Certiorari is not an ordinary appeal. It is used when a lower court or tribunal acted so unreasonably or outside its authority that its decision should be struck down, and there's no other adequate remedy available.",
    why: "Confusing certiorari with an ordinary appeal is one of the most common mistakes law students make, and the distinction is heavily tested in Remedial Law.",
    example: "If a judge issues an order without giving a party any chance to be heard, a petition for certiorari may be filed to annul that order for grave abuse of discretion.",
    memory_tip: "Certiorari = 'certain error' so severe it needs to be corrected outside the normal appeal process.",
    latin: "From certiorare, 'to be informed of' — historically a writ ordering the record of a case to be sent up for review.",
    related_laws: ["Rule 65, Rules of Court"],
    cases: [],
    related: ["Procedural Law", "Judicial Review"],
  },
  {
    term: "Bad Faith",
    category: CATEGORIES.CIVIL,
    difficulty: "intermediate",
    simple: "Acting with dishonest intent or knowledge of a defect, not just making an honest mistake.",
    legal: "A state of mind affirmatively operating with furtive design or with some motive of self-interest, ill will, or ulterior purpose, distinguished from mere negligence or honest error in judgment.",
    beginner: "Bad faith means someone knew something was wrong, or acted dishonestly on purpose, rather than simply making an innocent mistake. Good faith is its opposite: honest belief that one's actions are proper.",
    why: "Whether a party acted in good or bad faith often decides the amount of damages recoverable, particularly moral and exemplary damages.",
    example: "A seller who knowingly sells stolen property acts in bad faith, unlike a buyer who honestly did not know the property was stolen.",
    memory_tip: "Bad faith = knowingly bad, not just an honest mistake.",
    latin: null,
    related_laws: ["Article 19-21, Civil Code", "Article 2220, Civil Code"],
    cases: [],
    related: ["Estoppel", "Capacity (to Act)"],
  },
  {
    term: "Statute",
    category: CATEGORIES.GEN,
    difficulty: "beginner",
    simple: "A written law formally passed by the legislature.",
    legal: "A law enacted by the legislative branch of government, as distinguished from case law, executive issuances, or customary law.",
    beginner: "When people say 'the law says,' they are often referring to a statute, meaning a formal law passed by Congress and signed or otherwise made effective.",
    why: "Statutory construction, the science of interpreting statutes, is its own major topic tested in both Civil Law and Statutory Construction subjects.",
    example: "The Revised Penal Code, Act No. 3815, is a statute passed to define crimes and penalties.",
    memory_tip: "Statute sounds like 'stated' law — a law that has been formally stated in writing.",
    latin: null,
    related_laws: ["Article 2, Civil Code"],
    cases: ["Tañada v. Tuvera"],
    related: ["Jurisprudence", "Doctrine", "Mandatory Law"],
  },
  {
    term: "Doctrine",
    category: CATEGORIES.GEN,
    difficulty: "beginner",
    simple: "A legal principle or rule established through court decisions.",
    legal: "A rule, principle, or theory of law that has been settled through repeated application in judicial decisions and is recognized and applied by the courts.",
    beginner: "A doctrine is a named rule that judges keep applying once a court establishes it, like a legal shortcut everyone recognizes by name.",
    why: "Bar exams often ask students to identify or apply a named doctrine, so knowing the doctrine's name and origin case matters as much as knowing its content.",
    example: "The 'operative fact doctrine,' which recognizes the effects of a law before it is declared unconstitutional, is a doctrine developed through jurisprudence.",
    memory_tip: "Doctrine = a 'doctor's prescription' the courts keep applying to similar legal illnesses.",
    latin: null,
    related_laws: [],
    cases: [],
    related: ["Jurisprudence", "Stare Decisis"],
  },
  {
    term: "Separation of Powers",
    category: CATEGORIES.CONST,
    difficulty: "intermediate",
    simple: "Government power is divided among three separate branches so no single branch has too much power.",
    legal: "A constitutional principle that allocates governmental power among the legislative, executive, and judicial departments, each supreme within its own sphere, to prevent the concentration of power and provide a system of checks and balances.",
    beginner: "Congress makes laws, the President enforces them, and the courts interpret them. Each branch is meant to check the others so that no single branch becomes too powerful.",
    why: "This principle underlies major Constitutional Law doctrines like the political question doctrine and the scope of judicial review.",
    example: "Courts generally cannot be compelled to review purely political questions committed by the Constitution to Congress or the President, out of respect for separation of powers.",
    memory_tip: "Three branches, three separate boxes of power.",
    latin: null,
    related_laws: ["1987 Constitution, Articles VI, VII, VIII"],
    cases: ["Angara v. Electoral Commission"],
    related: ["Judicial Review", "Bill of Rights"],
  },
  {
    term: "Judicial Review",
    category: CATEGORIES.CONST,
    difficulty: "intermediate",
    simple: "The power of courts to declare a law or government act unconstitutional.",
    legal:
      "The power of the courts, particularly the Supreme Court, to determine whether an act of a co-equal branch of government has been done with grave abuse of discretion, or whether a law or treaty is unconstitutional, given an actual case or controversy and a proper party with legal standing.",
    beginner: "Judicial review lets courts act as a check on Congress and the President by striking down laws or actions that violate the Constitution, but only when there's an actual live dispute, not a hypothetical question.",
    why: "The requisites for judicial review, an actual case, standing, earliest opportunity, and the issue of constitutionality being the very lis mota, are constantly tested together.",
    example: "In Angara v. Electoral Commission, the Supreme Court explained its power to review acts of the legislature to determine whether they conform to the Constitution.",
    memory_tip: "Judicial review = judges reviewing whether a law crosses the constitutional line.",
    latin: null,
    related_laws: ["1987 Constitution, Article VIII, Section 1"],
    cases: ["Angara v. Electoral Commission"],
    related: ["Separation of Powers", "Certiorari"],
  },
  {
    term: "Ex Post Facto Law",
    category: CATEGORIES.MAXIM,
    difficulty: "intermediate",
    simple: "A law that punishes an act that was not a crime when it was committed, or increases the penalty after the fact.",
    legal:
      "A law that makes an act criminal which was innocent when done, aggravates a crime after it was committed, changes the punishment to a more severe one, alters the rules of evidence to make conviction easier, or deprives a person of a defense available at the time of the act, applied retroactively and to the disadvantage of the accused.",
    beginner: "The Constitution bans laws that reach backward in time to punish someone more harshly than the rules that existed when they acted.",
    why: "This is one of the clearest connections between Constitutional Law and Criminal Law, and it ties directly into the rule against retroactivity of penal laws.",
    example: "A law that increases the penalty for a crime already committed, and applies that harsher penalty to the accused, would be an unconstitutional ex post facto law.",
    memory_tip: "'Ex post facto' sounds like 'after the fact' — a law reaching back after the fact.",
    latin: "Ex (from/out of) + post (after) + facto (the fact/deed) — 'from after the fact.'",
    related_laws: ["1987 Constitution, Article III, Section 22"],
    cases: [],
    related: ["Retroactive (Retroactivity of Laws)", "Presumption of Innocence"],
  },
  {
    term: "Presumption of Innocence",
    category: CATEGORIES.CONST,
    difficulty: "beginner",
    simple: "Every accused person is considered innocent until proven guilty beyond reasonable doubt.",
    legal: "A constitutional guarantee that the accused shall be presumed innocent until the contrary is proved, placing the burden on the prosecution to establish guilt beyond reasonable doubt.",
    beginner: "The accused does not have to prove innocence. The prosecution must prove guilt, and if there is reasonable doubt left over, the accused must be acquitted.",
    why: "This presumption shapes the entire structure of a criminal trial, including who has the burden of proof and what quantum of evidence is needed.",
    example: "If the prosecution's evidence leaves real doubt about whether the accused committed the crime, the court must acquit rather than convict on a guess.",
    memory_tip: "Presumed innocent until the prosecution proves otherwise beyond reasonable doubt.",
    latin: null,
    related_laws: ["1987 Constitution, Article III, Section 14(2)"],
    cases: [],
    related: ["Due Process", "Acquittal", "Ex Post Facto Law"],
  },
  {
    term: "Res Judicata",
    category: CATEGORIES.MAXIM,
    difficulty: "advanced",
    simple: "A matter already decided by a final court judgment cannot be relitigated between the same parties.",
    legal:
      "A doctrine providing that a final judgment on the merits, rendered by a court of competent jurisdiction, is conclusive as to the rights of the parties and their privies, barring a subsequent action involving the same parties, subject matter, and cause of action.",
    beginner: "Once a case has been finally decided, the same parties cannot simply file the same case again hoping for a different outcome. The matter is considered closed.",
    why: "Res judicata promotes finality of judgments and is a required element to check whenever a new case looks suspiciously similar to an old, already decided one.",
    example: "If a court already ruled with finality that a debt was fully paid, the same creditor cannot sue the same debtor again for that same debt.",
    memory_tip: "'Res judicata' sounds like 'the thing has been judged' — it's already judged, so it's closed.",
    latin: "Res (the thing/matter) + judicata (judged) — 'a matter already judged.'",
    related_laws: ["Rule 39, Rules of Court"],
    cases: [],
    related: ["Estoppel", "Stare Decisis"],
  },
  {
    term: "Stare Decisis",
    category: CATEGORIES.MAXIM,
    difficulty: "intermediate",
    simple: "Courts should follow previously decided cases when the facts are substantially the same.",
    legal:
      "A doctrine that once a court has settled a principle of law applicable to a certain set of facts, it will apply that principle to future cases with substantially the same facts, promoting stability and predictability in the legal system.",
    beginner: "This is why studying past Supreme Court decisions matters so much. Courts try to be consistent and generally follow their own prior rulings rather than deciding each similar case differently.",
    why: "Stare decisis is the reason jurisprudence carries real legal weight in the Philippines, and it explains why lawyers cite prior cases as authority.",
    example: "Once the Supreme Court rules on how a specific Civil Code provision should be interpreted, lower courts are expected to follow that same interpretation in similar future cases.",
    memory_tip: "'Stare decisis' sounds like 'stare at decisions' — courts stare at, and stick to, past decisions.",
    latin: "Stare (to stand) + decisis (decided things) — 'to stand by things decided.'",
    related_laws: ["Article 8, Civil Code"],
    cases: [],
    related: ["Jurisprudence", "Doctrine", "Res Judicata"],
  },
];

export const CATEGORY_LIST = Array.from(new Set(SEED_TERMS.map((t) => t.category)));

export const DIFF_META = {
  beginner: { label: "Beginner", emoji: "🟢", bg: "var(--green-light)", fg: "#3F5B3C", border: "var(--green)" },
  intermediate: { label: "Intermediate", emoji: "🟡", bg: "var(--yellow-light)", fg: "#7A5B14", border: "var(--yellow)" },
  advanced: { label: "Advanced", emoji: "🔴", bg: "var(--pink-light)", fg: "#7A3542", border: "var(--pink)" },
};
